<a href="https://colab.research.google.com/github/tgallach/8-23-19/blob/master/assignment%2008.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from numpy.random import choice
from matplotlib import pyplot as plt
%matplotlib inline

In [0]:

#1. Fisher's Test

In [0]:
# fill in you data
data = np.matrix( [[32,18],[11,19]])
print(data)

[[32 18]
 [11 19]]


In [0]:
#If her responses were completely random, what was the probability to obtain the given table?
# save your answer into =ptable= variable 

data.sum()

80

In [0]:
data.sum(axis=0)

matrix([[42, 38]])

In [0]:
data.sum(axis = 1)

matrix([[50],
        [30]])

In [0]:
import numpy as np 
from scipy.stats import fisher_exact
from scipy.stats import hypergeom


X =hypergeom(80,43,50)
vals = range(0,44)
probs = X.pmf(vals)
probs[ probs<=X.pmf(32)].sum()

0.021828691306254516

In [0]:
ptable = 0.021828691306254516

In [0]:
# Use two-sided exact test to check for statistical significance.
# Calculate p-value and save it into variable pval

import numpy as np 
from scipy.stats import fisher_exact
data = np.matrix( [[33,17],[9,21]])
_, pval = fisher_exact(data,alternative="two-sided")
print(pval)

0.002557332608682513


In [0]:
pval = 0.002557332608682513

In [0]:
#2. Bootsrap Confidence Interval

In [0]:
# TODO: load the file "tennis2.csv"
PATH = ("https://github.com/utk-ie516/lectures-release-fall2019/blob/master/data/tennis.csv")
speed = pd.read_csv(PATH, sep = "")
speed.head()


HTTPError: ignored

In [0]:
# TODO: display the first rows

In [0]:
# TODO: select the column speed1 and save it into the variable "speed1"

In [0]:
# TODO: select the column speed2 and save it into the variable "speed2"

In [0]:
# TODO: create a new vector =diff= that shows the differences 
# of the measurements produced by the two systems.
diff = 0

In [0]:
# fix the following code by replacing the question marks 
# You code should collect average difference 
# for different bootstrap samples

np.random.seed(777) # set random seed (don't change this!)
B = 10000 # number of bootstrap sample (don't change this!)
bootstrapmeans = []
for i in range(B):
    #bootsample =  choice(???,???,replace=???)
    #bootstrapmeans.append(bootsample.mean()) 
    i = i

In [0]:
# plot the histogram of bootsraped average diffs
#_ = plt.hist(bootstrapmeans,rwidth=0.9,bins=20)

In [0]:
# calculate the confidence interval 
#L,U = np.percentile(bootstrapmeans, [???,???])
#print("\n bootstrap (perc) CI:",L,U,",  while the average observed difference is ",diff.mean())